# Generated by Django 5.0 on 2023-12-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_watchlist_avg_rating_watchlist_numner_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='numner_rating',
            new_name='number_rating',
        ),
    ]
